---
destination : /mnt/ohome/blog/site
auto        : false
lsi         : false
pygments    : true
permalink   : none
markdown    : maruku

maruku:
    use_divs: true
    use_tex: true
    png_engine : blahtex
    png_dir    : images/latex/
    png_url    : /images/latex/


# site related
blog:
    name    : Software Artisan
    description :  A programmer's thought

author      : Tang Ling
domain      : http://jsuper.github.io
    
